### ISSUE TITLE
Allow Players to Submit Ideas Anonymously

### ISSUE THREAD

**Issue by connor7000** [mc-ascendancy/ascendancy#10]
From **NovaStorm93#9909** on Discord:

"idealy use the bot to submit posts anonymously"

Just to re-write my understanding of this idea for clarity: "We should ideally create a feature through AscendBot such that players can submit ideas anonymously to then be forwarded into the #ideas channel."

**Comment by connor7000** [comment]
I'm not sure how tricky the implementation of this feature might be... but the ball is in your court, @brussels-sprout.

I'd wonder how we might be able to log who submits what ideas-- even if they are posted to the general server community anonymously. I'd like the data on who submits what such that we can follow-up for more information or give credit!

I also wonder if this idea is rendered obsolete by our creation of this page. Who knows?

**Comment by VolticFroogo** [comment]
I personally dislike the idea of anonymity for ideas as firstly, I believe ideas should be credited (as here), and second it could allow for abuse/trolling.

This idea would also be made redundant by issue #13.

**Comment by brussels-sprout** [comment]
I agree and want to add that anonymous ideas can't be discussed as they are now if the person sending them is anonymous. I don't see a reason for anonymous ideas.

**Comment by VolticFroogo** [comment]
@connor7000, what are your thoughts on this, do you think this has any reason to stay open?

**Comment by connor7000** [comment]
These are legitimate reasons to reject this idea. It may be closed!
