### ISSUE TITLE
Add World Border Warp

### ISSUE THREAD

**Issue by VolticFroogo** [mc-ascendancy/ascendancy#115]
From **Spenske#4509** on Discord:

"[Make it so] hitting the wold border sends you to the opposite border (ex -3412x,- 6000z sends you to -3412x. +6000z)."

**Comment by VolticFroogo** [comment]
Despite this idea being quite weird, I kinda like it.

This may be impractical with stuff like bridges, which to be mirrored on the edge would probably require quite a bit of development. Though I don't know if an open-source plugin which does this exists.

For players travelling in boats, this idea would be quite cool though, as it would probably be relatively seamless.

**Comment by connor7000** [comment]
An open-source plugin exists that does this, though I have never seen it be configured to a point that doesn't cause lag.

Regardless, for conceptual reasons moving into the future, this idea isn't compatible at this time. Not to mention the map was designed without this functionality in mind.
