### ISSUE TITLE
Add Larger Nation Title Entry Message

### ISSUE THREAD

**Issue by connor7000** [mc-ascendancy/ascendancy#22]
From **flushed#1337** on Discord:

"When you walk into someone else's nation, [make it so] the message isn't in the chat but as like, a message in the middle of your screen."

**Comment by VolticFroogo** [comment]
I'm going to fast track this one to in progress, as it is already on the internal board and has been discussed between staff.

**Comment by connor7000** [comment]
@VolticFroogo has begun to discuss this idea internally, writing:

"This, unlike the current configurable messages, will be more of a static message. This would be to prevent abuse, and be a more reliable entry message."

I will continue to forward any internal updates from there to here!

**Comment by VolticFroogo** [comment]
Whoops, we both posted the same thing, but I did it *one second* before you. Get rekt. xd

**Comment by VolticFroogo** [comment]
Implemented in AscendNations v0.2.8; closed.
