### ISSUE TITLE
Buff XP-Gain from Common Hostile Mobs

### ISSUE THREAD

**Issue by brussels-sprout** [mc-ascendancy/ascendancy#221]
From **plowingmonkey#3318** on Discord:

> make common mobs (zombies, skeletons, spiders, etc) drop twice the vanilla exp

**Comment by brussels-sprout** [comment]
This is a good idea since it's diffcult to get experience but doubling it may be too much.

**Comment by connor7000** [comment]
Could we close this issue and combine it with #29, @brussels-sprout? (Like add it as a comment there as a proposed solution.)

**Comment by brussels-sprout** [comment]
Duplicate of #29
