### ISSUE TITLE
Add Modified Villagers

### ISSUE THREAD

**Issue by brussels-sprout** [mc-ascendancy/ascendancy#223]
From **plowingmonkey#3318** on Discord:

> Add villagers but change the trades so they are less op and make them hard to breed, etc. Just make it so they can be used to obtain items that would normally prolong boring parts of gameplay (tools, whatever)

**Comment by connor7000** [comment]
Could we close this issue and combine it with #133, @brussels-sprout? (Like add it as a comment there as a proposed solution.)

**Comment by brussels-sprout** [comment]
Duplicate of #133
