### ISSUE TITLE
Change Global Chat Colour

### ISSUE THREAD

**Issue by brussels-sprout** [mc-ascendancy/ascendancy#226]
From **Pants#4502** on Discord:

"Make [it so global] chat [is] white instead of grey."

**Comment by brussels-sprout** [comment]
Related to #225

**Comment by VolticFroogo** [comment]
Nation chat is now white as of issue #23, so I feel like leaving regular chat grey is actually a good thing.

**Comment by brussels-sprout** [comment]
I agree.

**Comment by connor7000** [comment]
> Nation chat is now white as of issue #23, so I feel like leaving regular chat grey is actually a good thing.

I agree! Now that they have been changed, there's no reason to make them both the same again!
