### ISSUE TITLE
Add Custom Nation Chat Color

### ISSUE THREAD

**Issue by connor7000** [mc-ascendancy/ascendancy#23]
From **sprout#6906** on Discord:

"Make chat text colour white instead of grey."

**Comment by VolticFroogo** [comment]
This is already on the internal board, fast tracking to in progress.

**Comment by connor7000** [comment]
Interestingly, **Sakai#5980** seems to have the same idea as @brussels-sprout on the DIscord!

@VolticFroogo has begun to discuss this idea internally, writing:

"Sakai suggested in ideas to make nation chat white as opposed to gray to stand out. I believe this is a good idea, so I'll add an option for this."

I will continue to forward any internal updates from there to here!

**Comment by VolticFroogo** [comment]
Implemented in AscendNations v0.2.8; closed.
