### ISSUE TITLE
Allow Certain Nation Commands on Trade Island

### ISSUE THREAD

**Issue by VolticFroogo** [mc-ascendancy/ascendancy#230]
From **scromble#7661** in #feedback:

> we're unable to use /nation chat at the trade island due to it being a nation command
could we get an exception for /nation chat?

**Comment by VolticFroogo** [comment]
I believe this should be added, as some commands (such as `/nation chat`) should definitely be available when on the trade island.

@mervinvb, could you provide insight as to why this is currently blocked, as I don't see any commands which would be harmful to be accessible on the trade island?

**Comment by mervinvb** [comment]
I'm scared of people using the claim command there, and them using '/nation home' kinda breaks my system for checking wether or not someone is on the trade island. (As my plugin doesn't actually check for location, it just checks if they've been teleported there...) @VolticFroogo 

The `/nation chat` function should now be available again though, just programmed in a little bypass!

**Comment by VolticFroogo** [comment]
Ah, yeah, that makes sense. Well `/nation chat` was the only request command, and it should be the only one that is really needed.

Resolved.
