### ISSUE TITLE
Add Endermites

### ISSUE THREAD

**Issue by brussels-sprout** [mc-ascendancy/ascendancy#39]
From **LoomisFire#8565** in Discord:

"Add endermites."

**Comment by brussels-sprout** [comment]
I should add that the reason they suggested that is so enderman farms can work. I don't see a reason not to enable them.

**Comment by connor7000** [comment]
Yep.

This was an oversight by me, and it shouldn't take too long at all to add them. @NotARobotII, can you handle this? The spawn chance of the endermites should be rare-ish, but be sure to account for the hostile mob caps!

**Comment by NotARobotII** [comment]
They are enabled, this person just has bad luck getting them from ender pearls.

**Comment by brussels-sprout** [comment]
Are they the default spawn rates?

**Comment by NotARobotII** [comment]
Yes. They only spawn from ender pearls and I have no idea how you would modify that value so I couldn't have done it.

**Comment by brussels-sprout** [comment]
Alright.
